service: cupo-vehicular-api
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs24.x
  region: us-east-1
  stage: dev
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}

functions:
  api:
    handler: src/handler.main
    events:
      - httpApi: 'GET /salud'
      - httpApi: 'POST /colaboradores'
      - httpApi: 'PUT /colaboradores/{cedula}/cupo'
      - httpApi: 'POST /colaboradores/{cedula}/acreditaciones'
      - httpApi: 'POST /facturas'
      - httpApi: 'POST /sincronizaciones/facturas'
      - httpApi: 'POST /sincronizaciones/gasclub'

# endpoints

plugins:
  - serverless-offline